# Generated by cucumber-sinatra. (2014-07-21 21:54:27 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', './lib/test.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Test

class TestWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  TestWorld.new
end
